destination: /srv/dist
permalink:  /:categories/:title
collections:
  team_members:
    sort_by:  name
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  style: compressed
