destination: /srv/dist
permalink:  /:categories/:title
collections:
  team_members:
    sort_by:  name
  writeups:
    sort_by: date
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    scope:
      path: ""
      type: writeups
    values:
      layout: "writeup"
sass:
  style: compressed
  sourcemap: never
